//! star-params: embeds `parametersDefault` as a byte slice (equivalent to the
//! C++ `parametersDefault.xxd` generated by `xxd -i`) and ports the
//! `Parameters` machinery.
//!
//! Layers currently ported:
//! - `PARAMETERS_DEFAULT`: raw bytes of the default parameter file. Used by
//!   `STAR --help` to replicate the original tool's output byte-for-byte.
//! - Stub module for `Parameters` struct (filled out in M2).

pub mod defaults;
pub mod parameters;
pub mod sam_attributes;

pub use defaults::*;
